version: "3.11"

services:
  app:
    build:
      context: .
      args:
        UID: ${UID}
        GID: ${GID}
        FLASK_APP: webapi
        FLASK_ENV: ${env}
    env_file:
      - ./.env
    ports:
      - 5001:5000
    volumes:
      - ./setup.sh:/opt/setup.sh
      - ./src:/opt/python-webapp
    tty: true
    entrypoint: [ "/bin/sh" , "opt/setup.sh" ]
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:14.4-alpine
    ports:
      - 5432:5432
    tty: true
    env_file:
      - ./.env
    environment:
      TZ: America/Sao_Paulo
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "80:80"
